baseURL = "/"
languageCode = "en-us"
title = "Melvin's digital garden"
theme = "cortex"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
email = "melvinzhang@gmail.com"
footer = "Icon by Freepik. Built with Hugo and cortex."

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "friendly"
    tabWidth = 4
